repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: shfmt
        name: Format shell scripts with shfmt
        language: system
        types: [shell]
        entry: uv run --frozen shfmt
        args: [--write]

      - id: shellcheck
        name: Lint shell scripts with shellcheck
        language: system
        types: [shell]
        entry: uv run --frozen shellcheck

      - id: ruff-check
        name: Fix using Ruff
        language: system
        types: [python]
        entry: uv run --frozen ruff check
        args: [--fix]

      - id: ruff-format
        name: Format using Ruff
        language: system
        types: [python]
        entry: uv run --frozen ruff format

      - id: mypy
        name: Type check with mypy
        language: system
        types: [python]
        pass_filenames: false
        entry: uv run --frozen mypy
        args: [--show-error-codes, --pretty, .]

ci:
  autofix_prs: true
  autoupdate_schedule: quarterly
